//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlsInfoInitParameters) DeepCopyInto(out *ControlsInfoInitParameters) {
	*out = *in
	if in.ControlType != nil {
		in, out := &in.ControlType, &out.ControlType
		*out = new(string)
		**out = **in
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlsInfoInitParameters.
func (in *ControlsInfoInitParameters) DeepCopy() *ControlsInfoInitParameters {
	if in == nil {
		return nil
	}
	out := new(ControlsInfoInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlsInfoObservation) DeepCopyInto(out *ControlsInfoObservation) {
	*out = *in
	if in.ControlType != nil {
		in, out := &in.ControlType, &out.ControlType
		*out = new(string)
		**out = **in
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlsInfoObservation.
func (in *ControlsInfoObservation) DeepCopy() *ControlsInfoObservation {
	if in == nil {
		return nil
	}
	out := new(ControlsInfoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlsInfoParameters) DeepCopyInto(out *ControlsInfoParameters) {
	*out = *in
	if in.ControlType != nil {
		in, out := &in.ControlType, &out.ControlType
		*out = new(string)
		**out = **in
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlsInfoParameters.
func (in *ControlsInfoParameters) DeepCopy() *ControlsInfoParameters {
	if in == nil {
		return nil
	}
	out := new(ControlsInfoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomControlsInitParameters) DeepCopyInto(out *CustomControlsInitParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionValue != nil {
		in, out := &in.ActionValue, &out.ActionValue
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomControlsInitParameters.
func (in *CustomControlsInitParameters) DeepCopy() *CustomControlsInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomControlsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomControlsObservation) DeepCopyInto(out *CustomControlsObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionValue != nil {
		in, out := &in.ActionValue, &out.ActionValue
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomControlsObservation.
func (in *CustomControlsObservation) DeepCopy() *CustomControlsObservation {
	if in == nil {
		return nil
	}
	out := new(CustomControlsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomControlsParameters) DeepCopyInto(out *CustomControlsParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionValue != nil {
		in, out := &in.ActionValue, &out.ActionValue
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomControlsParameters.
func (in *CustomControlsParameters) DeepCopy() *CustomControlsParameters {
	if in == nil {
		return nil
	}
	out := new(CustomControlsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedControlsInitParameters) DeepCopyInto(out *PredefinedControlsInitParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionValue != nil {
		in, out := &in.ActionValue, &out.ActionValue
		*out = new(string)
		**out = **in
	}
	if in.ControlType != nil {
		in, out := &in.ControlType, &out.ControlType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProtocolType != nil {
		in, out := &in.ProtocolType, &out.ProtocolType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedControlsInitParameters.
func (in *PredefinedControlsInitParameters) DeepCopy() *PredefinedControlsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PredefinedControlsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedControlsObservation) DeepCopyInto(out *PredefinedControlsObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionValue != nil {
		in, out := &in.ActionValue, &out.ActionValue
		*out = new(string)
		**out = **in
	}
	if in.ControlType != nil {
		in, out := &in.ControlType, &out.ControlType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProtocolType != nil {
		in, out := &in.ProtocolType, &out.ProtocolType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedControlsObservation.
func (in *PredefinedControlsObservation) DeepCopy() *PredefinedControlsObservation {
	if in == nil {
		return nil
	}
	out := new(PredefinedControlsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedControlsParameters) DeepCopyInto(out *PredefinedControlsParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionValue != nil {
		in, out := &in.ActionValue, &out.ActionValue
		*out = new(string)
		**out = **in
	}
	if in.ControlType != nil {
		in, out := &in.ControlType, &out.ControlType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProtocolType != nil {
		in, out := &in.ProtocolType, &out.ProtocolType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedControlsParameters.
func (in *PredefinedControlsParameters) DeepCopy() *PredefinedControlsParameters {
	if in == nil {
		return nil
	}
	out := new(PredefinedControlsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Profile) DeepCopyInto(out *Profile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Profile.
func (in *Profile) DeepCopy() *Profile {
	if in == nil {
		return nil
	}
	out := new(Profile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Profile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileInitParameters) DeepCopyInto(out *ProfileInitParameters) {
	*out = *in
	if in.AssociateAllControls != nil {
		in, out := &in.AssociateAllControls, &out.AssociateAllControls
		*out = new(bool)
		**out = **in
	}
	if in.CommonGlobalOverrideActionsConfig != nil {
		in, out := &in.CommonGlobalOverrideActionsConfig, &out.CommonGlobalOverrideActionsConfig
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ControlsInfo != nil {
		in, out := &in.ControlsInfo, &out.ControlsInfo
		*out = make([]ControlsInfoInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomControls != nil {
		in, out := &in.CustomControls, &out.CustomControls
		*out = make([]CustomControlsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalControlActions != nil {
		in, out := &in.GlobalControlActions, &out.GlobalControlActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncarnationNumber != nil {
		in, out := &in.IncarnationNumber, &out.IncarnationNumber
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ParanoiaLevel != nil {
		in, out := &in.ParanoiaLevel, &out.ParanoiaLevel
		*out = new(string)
		**out = **in
	}
	if in.PredefinedControls != nil {
		in, out := &in.PredefinedControls, &out.PredefinedControls
		*out = make([]PredefinedControlsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PredefinedControlsVersion != nil {
		in, out := &in.PredefinedControlsVersion, &out.PredefinedControlsVersion
		*out = new(string)
		**out = **in
	}
	if in.WebSocketControls != nil {
		in, out := &in.WebSocketControls, &out.WebSocketControls
		*out = make([]WebSocketControlsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileInitParameters.
func (in *ProfileInitParameters) DeepCopy() *ProfileInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProfileInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileList) DeepCopyInto(out *ProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Profile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileList.
func (in *ProfileList) DeepCopy() *ProfileList {
	if in == nil {
		return nil
	}
	out := new(ProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileObservation) DeepCopyInto(out *ProfileObservation) {
	*out = *in
	if in.AssociateAllControls != nil {
		in, out := &in.AssociateAllControls, &out.AssociateAllControls
		*out = new(bool)
		**out = **in
	}
	if in.CommonGlobalOverrideActionsConfig != nil {
		in, out := &in.CommonGlobalOverrideActionsConfig, &out.CommonGlobalOverrideActionsConfig
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ControlsInfo != nil {
		in, out := &in.ControlsInfo, &out.ControlsInfo
		*out = make([]ControlsInfoObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomControls != nil {
		in, out := &in.CustomControls, &out.CustomControls
		*out = make([]CustomControlsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalControlActions != nil {
		in, out := &in.GlobalControlActions, &out.GlobalControlActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncarnationNumber != nil {
		in, out := &in.IncarnationNumber, &out.IncarnationNumber
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ParanoiaLevel != nil {
		in, out := &in.ParanoiaLevel, &out.ParanoiaLevel
		*out = new(string)
		**out = **in
	}
	if in.PredefinedControls != nil {
		in, out := &in.PredefinedControls, &out.PredefinedControls
		*out = make([]PredefinedControlsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PredefinedControlsVersion != nil {
		in, out := &in.PredefinedControlsVersion, &out.PredefinedControlsVersion
		*out = new(string)
		**out = **in
	}
	if in.WebSocketControls != nil {
		in, out := &in.WebSocketControls, &out.WebSocketControls
		*out = make([]WebSocketControlsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileObservation.
func (in *ProfileObservation) DeepCopy() *ProfileObservation {
	if in == nil {
		return nil
	}
	out := new(ProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileParameters) DeepCopyInto(out *ProfileParameters) {
	*out = *in
	if in.AssociateAllControls != nil {
		in, out := &in.AssociateAllControls, &out.AssociateAllControls
		*out = new(bool)
		**out = **in
	}
	if in.CommonGlobalOverrideActionsConfig != nil {
		in, out := &in.CommonGlobalOverrideActionsConfig, &out.CommonGlobalOverrideActionsConfig
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ControlsInfo != nil {
		in, out := &in.ControlsInfo, &out.ControlsInfo
		*out = make([]ControlsInfoParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomControls != nil {
		in, out := &in.CustomControls, &out.CustomControls
		*out = make([]CustomControlsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalControlActions != nil {
		in, out := &in.GlobalControlActions, &out.GlobalControlActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncarnationNumber != nil {
		in, out := &in.IncarnationNumber, &out.IncarnationNumber
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ParanoiaLevel != nil {
		in, out := &in.ParanoiaLevel, &out.ParanoiaLevel
		*out = new(string)
		**out = **in
	}
	if in.PredefinedControls != nil {
		in, out := &in.PredefinedControls, &out.PredefinedControls
		*out = make([]PredefinedControlsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PredefinedControlsVersion != nil {
		in, out := &in.PredefinedControlsVersion, &out.PredefinedControlsVersion
		*out = new(string)
		**out = **in
	}
	if in.WebSocketControls != nil {
		in, out := &in.WebSocketControls, &out.WebSocketControls
		*out = make([]WebSocketControlsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileParameters.
func (in *ProfileParameters) DeepCopy() *ProfileParameters {
	if in == nil {
		return nil
	}
	out := new(ProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileSpec) DeepCopyInto(out *ProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileSpec.
func (in *ProfileSpec) DeepCopy() *ProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileStatus) DeepCopyInto(out *ProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileStatus.
func (in *ProfileStatus) DeepCopy() *ProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebSocketControlsInitParameters) DeepCopyInto(out *WebSocketControlsInitParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionValue != nil {
		in, out := &in.ActionValue, &out.ActionValue
		*out = new(string)
		**out = **in
	}
	if in.ControlType != nil {
		in, out := &in.ControlType, &out.ControlType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProtocolType != nil {
		in, out := &in.ProtocolType, &out.ProtocolType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSocketControlsInitParameters.
func (in *WebSocketControlsInitParameters) DeepCopy() *WebSocketControlsInitParameters {
	if in == nil {
		return nil
	}
	out := new(WebSocketControlsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebSocketControlsObservation) DeepCopyInto(out *WebSocketControlsObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionValue != nil {
		in, out := &in.ActionValue, &out.ActionValue
		*out = new(string)
		**out = **in
	}
	if in.ControlType != nil {
		in, out := &in.ControlType, &out.ControlType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProtocolType != nil {
		in, out := &in.ProtocolType, &out.ProtocolType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSocketControlsObservation.
func (in *WebSocketControlsObservation) DeepCopy() *WebSocketControlsObservation {
	if in == nil {
		return nil
	}
	out := new(WebSocketControlsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebSocketControlsParameters) DeepCopyInto(out *WebSocketControlsParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionValue != nil {
		in, out := &in.ActionValue, &out.ActionValue
		*out = new(string)
		**out = **in
	}
	if in.ControlType != nil {
		in, out := &in.ControlType, &out.ControlType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProtocolType != nil {
		in, out := &in.ProtocolType, &out.ProtocolType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSocketControlsParameters.
func (in *WebSocketControlsParameters) DeepCopy() *WebSocketControlsParameters {
	if in == nil {
		return nil
	}
	out := new(WebSocketControlsParameters)
	in.DeepCopyInto(out)
	return out
}
