/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/zscaler/crossplane-provider-zpa/apis/zpasegmentgroup/v1alpha1"
	v1alpha11 "github.com/zscaler/crossplane-provider-zpa/apis/zpaservergroup/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Segment.
func (mg *Segment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SegmentGroupID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SegmentGroupIDRef,
		Selector:     mg.Spec.ForProvider.SegmentGroupIDSelector,
		To: reference.To{
			List:    &v1alpha1.GroupList{},
			Managed: &v1alpha1.Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SegmentGroupID")
	}
	mg.Spec.ForProvider.SegmentGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SegmentGroupIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.ServerGroups); i3++ {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.ServerGroups[i3].ID),
			Extract:       reference.ExternalName(),
			References:    mg.Spec.ForProvider.ServerGroups[i3].IDRefs,
			Selector:      mg.Spec.ForProvider.ServerGroups[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha11.GroupList{},
				Managed: &v1alpha11.Group{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ServerGroups[i3].ID")
		}
		mg.Spec.ForProvider.ServerGroups[i3].ID = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.ServerGroups[i3].IDRefs = mrsp.ResolvedReferences

	}

	return nil
}
