apiVersion: zpalssconfigcontroller.zpa.crossplane.io/v1alpha1
kind: ConfigController
metadata:
  annotations:
    meta.upbound.io/example-id: zpalssconfigcontroller/v1alpha1/configcontroller
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    config:
    - description: Example
      enabled: true
      filter:
      - ZPN_STATUS_AUTH_FAILED
      - ZPN_STATUS_DISCONNECTED
      - ZPN_STATUS_AUTHENTICATED
      format: ${data.zpa_lss_config_log_type_formats.zpn_ast_auth_log.json}
      lssHost: splunk.acme.com
      lssPort: "11000"
      name: Example
      sourceLogType: zpn_ast_auth_log
      useTls: true
    connectorGroups:
    - id:
      - ${zpa_app_connector_group.example.id}

---

