/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ApplicationsInitParameters struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ApplicationsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ApplicationsParameters struct {

	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type GroupInitParameters struct {
	Applications []ApplicationsInitParameters `json:"applications,omitempty" tf:"applications,omitempty"`

	// Description of the segment group.
	// Description of the app group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Whether this segment group is enabled or not.
	// Whether this app group is enabled or not.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Name of the segment group.
	// Name of the app group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PolicyMigrated *bool `json:"policyMigrated,omitempty" tf:"policy_migrated,omitempty"`

	TCPKeepAliveEnabled *string `json:"tcpKeepAliveEnabled,omitempty" tf:"tcp_keep_alive_enabled,omitempty"`
}

type GroupObservation struct {
	Applications []ApplicationsObservation `json:"applications,omitempty" tf:"applications,omitempty"`

	// Description of the segment group.
	// Description of the app group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Whether this segment group is enabled or not.
	// Whether this app group is enabled or not.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the segment group.
	// Name of the app group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PolicyMigrated *bool `json:"policyMigrated,omitempty" tf:"policy_migrated,omitempty"`

	TCPKeepAliveEnabled *string `json:"tcpKeepAliveEnabled,omitempty" tf:"tcp_keep_alive_enabled,omitempty"`
}

type GroupParameters struct {

	// +kubebuilder:validation:Optional
	Applications []ApplicationsParameters `json:"applications,omitempty" tf:"applications,omitempty"`

	// Description of the segment group.
	// Description of the app group.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Whether this segment group is enabled or not.
	// Whether this app group is enabled or not.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Name of the segment group.
	// Name of the app group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	PolicyMigrated *bool `json:"policyMigrated,omitempty" tf:"policy_migrated,omitempty"`

	// +kubebuilder:validation:Optional
	TCPKeepAliveEnabled *string `json:"tcpKeepAliveEnabled,omitempty" tf:"tcp_keep_alive_enabled,omitempty"`
}

// GroupSpec defines the desired state of Group
type GroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupInitParameters `json:"initProvider,omitempty"`
}

// GroupStatus defines the observed state of Group.
type GroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Group is the Schema for the Groups API. Creates and manages ZPA Segment Group resource
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,zpa}
type Group struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || has(self.initProvider.name)",message="name is a required parameter"
	Spec   GroupSpec   `json:"spec"`
	Status GroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupList contains a list of Groups
type GroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Group `json:"items"`
}

// Repository type metadata.
var (
	Group_Kind             = "Group"
	Group_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Group_Kind}.String()
	Group_KindAPIVersion   = Group_Kind + "." + CRDGroupVersion.String()
	Group_GroupVersionKind = CRDGroupVersion.WithKind(Group_Kind)
)

func init() {
	SchemeBuilder.Register(&Group{}, &GroupList{})
}
