/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/zscaler/provider-zpa/apis/v1alpha1"
	v1beta1 "github.com/zscaler/provider-zpa/apis/v1beta1"
	v1alpha1zpaaccessrule "github.com/zscaler/provider-zpa/apis/zpaaccessrule/v1alpha1"
	v1alpha1zpaapplicationserver "github.com/zscaler/provider-zpa/apis/zpaapplicationserver/v1alpha1"
	v1alpha1zpaforwardingrule "github.com/zscaler/provider-zpa/apis/zpaforwardingrule/v1alpha1"
	v1alpha1zpainspectionrule "github.com/zscaler/provider-zpa/apis/zpainspectionrule/v1alpha1"
	v1alpha1zpaprovisioningkey "github.com/zscaler/provider-zpa/apis/zpaprovisioningkey/v1alpha1"
	v1alpha1zpasegmentgroup "github.com/zscaler/provider-zpa/apis/zpasegmentgroup/v1alpha1"
	v1alpha1zpatimeoutrule "github.com/zscaler/provider-zpa/apis/zpatimeoutrule/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1zpaaccessrule.SchemeBuilder.AddToScheme,
		v1alpha1zpaapplicationserver.SchemeBuilder.AddToScheme,
		v1alpha1zpaforwardingrule.SchemeBuilder.AddToScheme,
		v1alpha1zpainspectionrule.SchemeBuilder.AddToScheme,
		v1alpha1zpaprovisioningkey.SchemeBuilder.AddToScheme,
		v1alpha1zpasegmentgroup.SchemeBuilder.AddToScheme,
		v1alpha1zpatimeoutrule.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
