//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsObservation) DeepCopyInto(out *ConditionsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Operands != nil {
		in, out := &in.Operands, &out.Operands
		*out = make([]OperandsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsObservation.
func (in *ConditionsObservation) DeepCopy() *ConditionsObservation {
	if in == nil {
		return nil
	}
	out := new(ConditionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsOperandsObservation) DeepCopyInto(out *ConditionsOperandsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsOperandsObservation.
func (in *ConditionsOperandsObservation) DeepCopy() *ConditionsOperandsObservation {
	if in == nil {
		return nil
	}
	out := new(ConditionsOperandsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsOperandsParameters) DeepCopyInto(out *ConditionsOperandsParameters) {
	*out = *in
	if in.IdpID != nil {
		in, out := &in.IdpID, &out.IdpID
		*out = new(string)
		**out = **in
	}
	if in.Lhs != nil {
		in, out := &in.Lhs, &out.Lhs
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectType != nil {
		in, out := &in.ObjectType, &out.ObjectType
		*out = new(string)
		**out = **in
	}
	if in.Rhs != nil {
		in, out := &in.Rhs, &out.Rhs
		*out = new(string)
		**out = **in
	}
	if in.RhsList != nil {
		in, out := &in.RhsList, &out.RhsList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsOperandsParameters.
func (in *ConditionsOperandsParameters) DeepCopy() *ConditionsOperandsParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionsOperandsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsParameters) DeepCopyInto(out *ConditionsParameters) {
	*out = *in
	if in.Negated != nil {
		in, out := &in.Negated, &out.Negated
		*out = new(bool)
		**out = **in
	}
	if in.Operands != nil {
		in, out := &in.Operands, &out.Operands
		*out = make([]OperandsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsParameters.
func (in *ConditionsParameters) DeepCopy() *ConditionsParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardingRule) DeepCopyInto(out *ForwardingRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardingRule.
func (in *ForwardingRule) DeepCopy() *ForwardingRule {
	if in == nil {
		return nil
	}
	out := new(ForwardingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForwardingRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardingRuleList) DeepCopyInto(out *ForwardingRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ForwardingRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardingRuleList.
func (in *ForwardingRuleList) DeepCopy() *ForwardingRuleList {
	if in == nil {
		return nil
	}
	out := new(ForwardingRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForwardingRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardingRuleObservation) DeepCopyInto(out *ForwardingRuleObservation) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardingRuleObservation.
func (in *ForwardingRuleObservation) DeepCopy() *ForwardingRuleObservation {
	if in == nil {
		return nil
	}
	out := new(ForwardingRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardingRuleParameters) DeepCopyInto(out *ForwardingRuleParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionID != nil {
		in, out := &in.ActionID, &out.ActionID
		*out = new(string)
		**out = **in
	}
	if in.BypassDefaultRule != nil {
		in, out := &in.BypassDefaultRule, &out.BypassDefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomMsg != nil {
		in, out := &in.CustomMsg, &out.CustomMsg
		*out = new(string)
		**out = **in
	}
	if in.DefaultRule != nil {
		in, out := &in.DefaultRule, &out.DefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LssDefaultRule != nil {
		in, out := &in.LssDefaultRule, &out.LssDefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.PolicySetID != nil {
		in, out := &in.PolicySetID, &out.PolicySetID
		*out = new(string)
		**out = **in
	}
	if in.PolicyType != nil {
		in, out := &in.PolicyType, &out.PolicyType
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(string)
		**out = **in
	}
	if in.ReauthDefaultRule != nil {
		in, out := &in.ReauthDefaultRule, &out.ReauthDefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.ReauthIdleTimeout != nil {
		in, out := &in.ReauthIdleTimeout, &out.ReauthIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.ReauthTimeout != nil {
		in, out := &in.ReauthTimeout, &out.ReauthTimeout
		*out = new(string)
		**out = **in
	}
	if in.RuleOrder != nil {
		in, out := &in.RuleOrder, &out.RuleOrder
		*out = new(string)
		**out = **in
	}
	if in.ZpnInspectionProfileID != nil {
		in, out := &in.ZpnInspectionProfileID, &out.ZpnInspectionProfileID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardingRuleParameters.
func (in *ForwardingRuleParameters) DeepCopy() *ForwardingRuleParameters {
	if in == nil {
		return nil
	}
	out := new(ForwardingRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardingRuleSpec) DeepCopyInto(out *ForwardingRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardingRuleSpec.
func (in *ForwardingRuleSpec) DeepCopy() *ForwardingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ForwardingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardingRuleStatus) DeepCopyInto(out *ForwardingRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardingRuleStatus.
func (in *ForwardingRuleStatus) DeepCopy() *ForwardingRuleStatus {
	if in == nil {
		return nil
	}
	out := new(ForwardingRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectionRule) DeepCopyInto(out *InspectionRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectionRule.
func (in *InspectionRule) DeepCopy() *InspectionRule {
	if in == nil {
		return nil
	}
	out := new(InspectionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectionRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectionRuleConditionsObservation) DeepCopyInto(out *InspectionRuleConditionsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Operands != nil {
		in, out := &in.Operands, &out.Operands
		*out = make([]ConditionsOperandsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectionRuleConditionsObservation.
func (in *InspectionRuleConditionsObservation) DeepCopy() *InspectionRuleConditionsObservation {
	if in == nil {
		return nil
	}
	out := new(InspectionRuleConditionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectionRuleConditionsParameters) DeepCopyInto(out *InspectionRuleConditionsParameters) {
	*out = *in
	if in.Negated != nil {
		in, out := &in.Negated, &out.Negated
		*out = new(bool)
		**out = **in
	}
	if in.Operands != nil {
		in, out := &in.Operands, &out.Operands
		*out = make([]ConditionsOperandsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectionRuleConditionsParameters.
func (in *InspectionRuleConditionsParameters) DeepCopy() *InspectionRuleConditionsParameters {
	if in == nil {
		return nil
	}
	out := new(InspectionRuleConditionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectionRuleList) DeepCopyInto(out *InspectionRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InspectionRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectionRuleList.
func (in *InspectionRuleList) DeepCopy() *InspectionRuleList {
	if in == nil {
		return nil
	}
	out := new(InspectionRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InspectionRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectionRuleObservation) DeepCopyInto(out *InspectionRuleObservation) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]InspectionRuleConditionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectionRuleObservation.
func (in *InspectionRuleObservation) DeepCopy() *InspectionRuleObservation {
	if in == nil {
		return nil
	}
	out := new(InspectionRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectionRuleParameters) DeepCopyInto(out *InspectionRuleParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionID != nil {
		in, out := &in.ActionID, &out.ActionID
		*out = new(string)
		**out = **in
	}
	if in.BypassDefaultRule != nil {
		in, out := &in.BypassDefaultRule, &out.BypassDefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]InspectionRuleConditionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomMsg != nil {
		in, out := &in.CustomMsg, &out.CustomMsg
		*out = new(string)
		**out = **in
	}
	if in.DefaultRule != nil {
		in, out := &in.DefaultRule, &out.DefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LssDefaultRule != nil {
		in, out := &in.LssDefaultRule, &out.LssDefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.PolicySetID != nil {
		in, out := &in.PolicySetID, &out.PolicySetID
		*out = new(string)
		**out = **in
	}
	if in.PolicyType != nil {
		in, out := &in.PolicyType, &out.PolicyType
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(string)
		**out = **in
	}
	if in.ReauthDefaultRule != nil {
		in, out := &in.ReauthDefaultRule, &out.ReauthDefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.ReauthIdleTimeout != nil {
		in, out := &in.ReauthIdleTimeout, &out.ReauthIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.ReauthTimeout != nil {
		in, out := &in.ReauthTimeout, &out.ReauthTimeout
		*out = new(string)
		**out = **in
	}
	if in.RuleOrder != nil {
		in, out := &in.RuleOrder, &out.RuleOrder
		*out = new(string)
		**out = **in
	}
	if in.ZpnInspectionProfileID != nil {
		in, out := &in.ZpnInspectionProfileID, &out.ZpnInspectionProfileID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectionRuleParameters.
func (in *InspectionRuleParameters) DeepCopy() *InspectionRuleParameters {
	if in == nil {
		return nil
	}
	out := new(InspectionRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectionRuleSpec) DeepCopyInto(out *InspectionRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectionRuleSpec.
func (in *InspectionRuleSpec) DeepCopy() *InspectionRuleSpec {
	if in == nil {
		return nil
	}
	out := new(InspectionRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectionRuleStatus) DeepCopyInto(out *InspectionRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectionRuleStatus.
func (in *InspectionRuleStatus) DeepCopy() *InspectionRuleStatus {
	if in == nil {
		return nil
	}
	out := new(InspectionRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandsObservation) DeepCopyInto(out *OperandsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandsObservation.
func (in *OperandsObservation) DeepCopy() *OperandsObservation {
	if in == nil {
		return nil
	}
	out := new(OperandsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandsParameters) DeepCopyInto(out *OperandsParameters) {
	*out = *in
	if in.IdpID != nil {
		in, out := &in.IdpID, &out.IdpID
		*out = new(string)
		**out = **in
	}
	if in.Lhs != nil {
		in, out := &in.Lhs, &out.Lhs
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectType != nil {
		in, out := &in.ObjectType, &out.ObjectType
		*out = new(string)
		**out = **in
	}
	if in.Rhs != nil {
		in, out := &in.Rhs, &out.Rhs
		*out = new(string)
		**out = **in
	}
	if in.RhsList != nil {
		in, out := &in.RhsList, &out.RhsList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandsParameters.
func (in *OperandsParameters) DeepCopy() *OperandsParameters {
	if in == nil {
		return nil
	}
	out := new(OperandsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRule) DeepCopyInto(out *TimeoutRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRule.
func (in *TimeoutRule) DeepCopy() *TimeoutRule {
	if in == nil {
		return nil
	}
	out := new(TimeoutRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeoutRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRuleConditionsObservation) DeepCopyInto(out *TimeoutRuleConditionsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Operands != nil {
		in, out := &in.Operands, &out.Operands
		*out = make([]TimeoutRuleConditionsOperandsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRuleConditionsObservation.
func (in *TimeoutRuleConditionsObservation) DeepCopy() *TimeoutRuleConditionsObservation {
	if in == nil {
		return nil
	}
	out := new(TimeoutRuleConditionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRuleConditionsOperandsObservation) DeepCopyInto(out *TimeoutRuleConditionsOperandsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRuleConditionsOperandsObservation.
func (in *TimeoutRuleConditionsOperandsObservation) DeepCopy() *TimeoutRuleConditionsOperandsObservation {
	if in == nil {
		return nil
	}
	out := new(TimeoutRuleConditionsOperandsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRuleConditionsOperandsParameters) DeepCopyInto(out *TimeoutRuleConditionsOperandsParameters) {
	*out = *in
	if in.IdpID != nil {
		in, out := &in.IdpID, &out.IdpID
		*out = new(string)
		**out = **in
	}
	if in.Lhs != nil {
		in, out := &in.Lhs, &out.Lhs
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectType != nil {
		in, out := &in.ObjectType, &out.ObjectType
		*out = new(string)
		**out = **in
	}
	if in.Rhs != nil {
		in, out := &in.Rhs, &out.Rhs
		*out = new(string)
		**out = **in
	}
	if in.RhsList != nil {
		in, out := &in.RhsList, &out.RhsList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRuleConditionsOperandsParameters.
func (in *TimeoutRuleConditionsOperandsParameters) DeepCopy() *TimeoutRuleConditionsOperandsParameters {
	if in == nil {
		return nil
	}
	out := new(TimeoutRuleConditionsOperandsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRuleConditionsParameters) DeepCopyInto(out *TimeoutRuleConditionsParameters) {
	*out = *in
	if in.Negated != nil {
		in, out := &in.Negated, &out.Negated
		*out = new(bool)
		**out = **in
	}
	if in.Operands != nil {
		in, out := &in.Operands, &out.Operands
		*out = make([]TimeoutRuleConditionsOperandsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRuleConditionsParameters.
func (in *TimeoutRuleConditionsParameters) DeepCopy() *TimeoutRuleConditionsParameters {
	if in == nil {
		return nil
	}
	out := new(TimeoutRuleConditionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRuleList) DeepCopyInto(out *TimeoutRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimeoutRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRuleList.
func (in *TimeoutRuleList) DeepCopy() *TimeoutRuleList {
	if in == nil {
		return nil
	}
	out := new(TimeoutRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeoutRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRuleObservation) DeepCopyInto(out *TimeoutRuleObservation) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TimeoutRuleConditionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRuleObservation.
func (in *TimeoutRuleObservation) DeepCopy() *TimeoutRuleObservation {
	if in == nil {
		return nil
	}
	out := new(TimeoutRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRuleParameters) DeepCopyInto(out *TimeoutRuleParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ActionID != nil {
		in, out := &in.ActionID, &out.ActionID
		*out = new(string)
		**out = **in
	}
	if in.BypassDefaultRule != nil {
		in, out := &in.BypassDefaultRule, &out.BypassDefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TimeoutRuleConditionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomMsg != nil {
		in, out := &in.CustomMsg, &out.CustomMsg
		*out = new(string)
		**out = **in
	}
	if in.DefaultRule != nil {
		in, out := &in.DefaultRule, &out.DefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LssDefaultRule != nil {
		in, out := &in.LssDefaultRule, &out.LssDefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.PolicySetID != nil {
		in, out := &in.PolicySetID, &out.PolicySetID
		*out = new(string)
		**out = **in
	}
	if in.PolicyType != nil {
		in, out := &in.PolicyType, &out.PolicyType
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(string)
		**out = **in
	}
	if in.ReauthDefaultRule != nil {
		in, out := &in.ReauthDefaultRule, &out.ReauthDefaultRule
		*out = new(bool)
		**out = **in
	}
	if in.ReauthIdleTimeout != nil {
		in, out := &in.ReauthIdleTimeout, &out.ReauthIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.ReauthTimeout != nil {
		in, out := &in.ReauthTimeout, &out.ReauthTimeout
		*out = new(string)
		**out = **in
	}
	if in.RuleOrder != nil {
		in, out := &in.RuleOrder, &out.RuleOrder
		*out = new(string)
		**out = **in
	}
	if in.ZpnInspectionProfileID != nil {
		in, out := &in.ZpnInspectionProfileID, &out.ZpnInspectionProfileID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRuleParameters.
func (in *TimeoutRuleParameters) DeepCopy() *TimeoutRuleParameters {
	if in == nil {
		return nil
	}
	out := new(TimeoutRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRuleSpec) DeepCopyInto(out *TimeoutRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRuleSpec.
func (in *TimeoutRuleSpec) DeepCopy() *TimeoutRuleSpec {
	if in == nil {
		return nil
	}
	out := new(TimeoutRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutRuleStatus) DeepCopyInto(out *TimeoutRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutRuleStatus.
func (in *TimeoutRuleStatus) DeepCopy() *TimeoutRuleStatus {
	if in == nil {
		return nil
	}
	out := new(TimeoutRuleStatus)
	in.DeepCopyInto(out)
	return out
}
